/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.behaviors.LbUX = {
    attach: function attach(context) {

      $('.layout-builder__actions .layout-builder__link').once().on('click', function (event) {
        $(event.currentTarget).parent().toggleClass('layout-builder__actions--display');
      });

      $(window).on('dialog:aftercreate', function (event, dialog, $element) {

        var id = $element.find('[data-layout-builder-target-highlight-id]').attr('data-layout-builder-target-highlight-id');
        if (id) {
          $('[data-layout-builder-highlight-id="' + id + '"]').addClass('layout-builder__block--selected');
        }
      });

      $(window).on('dialog:afterclose', function (event, dialog, $element) {

        $('.layout-builder__block--selected').removeClass('layout-builder__block--selected');
        if (Drupal.offCanvas.isOffCanvas($element)) {
          console.log("test");

          $('.layout-builder__actions--display').removeClass('layout-builder__actions--display');
        }
      });
    }
  };
})(jQuery, Drupal);